channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6
  - bioconda::tabix
  - gfortran_linux-64 #{{linux-only}}
  - clangxx_osx-64 #{{osx-only}}
  - libcurl #{{osx-only}}
  - ghostscript
  - gmp
  - libgit2 #{{osx-only}}
  - rstudio #{{osx-only}}
  - r-base=4.0.3
  - r-essentials
  - r-renv

  