
name: VitaminD_MR
channels:
  - conda-forge
  - r
  - bioconda
  - defaults

dependencies:
  - python>=3.6
  - r-tidyverse>=1.2
  - r-base==3.6.3
  - r-essentials=3.6.0
  - r-readxl>=1.3
  - rstudio>=1.1
  - r-ggplot2>=3  # needs channel conda-forge
  - r-ldlinkr>=1.0.0 # needs channel bioconda
  - r-curl>=3.3 
  - r-devtools