
name: VitaminD_MR
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
  - anaconda

dependencies:
  - python>=3.6
  - tabix
  - gfortran_linux-64=7.3
  - r::r-stringi
  - r-argparse
  - r-tidyverse>=1.2
  - r-base>=3.6.1
  - r-essentials=3.6
  - r-readxl>=1.3
  - rstudio>=1.1
  - r-ggplot2>=3  # needs channel conda-forge
  - r-ldlinkr>=1.0.0 # needs channel bioconda
  - r-curl>=3.3 
  - r-devtools
  - r-plotly
  - r-openxlsx
  - r-gmp
  - r-metafor
  - r-rio>=0.5.26
  - r-lme4
  - r-pbkrtest
  - r-car
  - r-mgsub

