name: docker-build-push

on:
  push:
    branches:
      - '**'

jobs:
  docker:
    env:
      dockerhub_repository: vitamin_d_mr_test
      dockerhub_organization: richardslab
      docker_tag_base: ${{dockerhub_organization}}/${{dockerhub_repository}}
    runs-on: ubuntu-latest
    steps:
      - 
        name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      -   
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - 
        uses: haya14busa/action-cond@v1
        id: tags
        with:
          cond: ${{ env.GITHUB_REF_SLUG == 'main' }}
          if_true: ${{env.branch_tag}},${{env.latest}}
          if_false: ${{env.branch_tag}}
        env:
          branch_tag: ${{env.docker_tag_base}}:${{steps.date.outputs.date}}_${{env.GITHUB_REF_SLUG}}
          latest_tag: ${{env.docker_tag_base}}:latest
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push branch
        uses: docker/build-push-action@v2
        with:
          context: installation
          push: true
          tags: ${{ steps.tags.outputs.value }}
