name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.6
        mamba-version: "*"
        channels: conda-forge,bioconda,r,defaults
        channel-priority: true
        activate-environment: anaconda-client-env
        environment-file: installation/environment.yaml
    - shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
          R --no-save < post_conda_steps.R
    - name: Lint with lintr
      run: |
        mamba install r-lintr
        R -e 'library(lintr); lint_dir("scripts")'