name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        installation/create_env.sh
    - name: Lint with flake8
      run: |
        mamba install -c conda-forge r-lintr
        R -e 'library(lintr); lint_dir("scripts")'
        
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
